[Added Morse Code 🚀] :  Added the morse code
d-coder111/SpectrumOfPython pull request #21
Opened 2024-10-19 19:07 UTC by Blacksujit

## added the Morse Code :

Added the Morse Code 

#hactobersfest2024

PR to issue no  --> #4

2024-10-21 00:23 UTC, d-coder111 requested changes
Add in the appropriate folder 📂. Kindly star this repo to show your support✨.

2024-10-21 05:59 UTC, Blacksujit commented
Please check the PR i have created an seperate python folder and added the python codes in it

2024-10-21 16:07 UTC, d-coder111 requested changes
See, the whole repo is all about python and out of the created folders, you have to choose to which particular folder(category) your program belongs to and add that into the folder. You don't have to create a new folder separately and if you have a bigger project then create a folder separately but choose the folder out of the created ones.
Kindly star the repository to show your support and encouragement. It’s designed to help programmers of all levels, from beginners to advanced, contribute and grow.

2024-10-21 16:16 UTC, Blacksujit commented
Cool understand 👍

2024-10-22 10:20 UTC, Blacksujit commented
can you review it once i have added the python codes in game galore and deleted the python codes folder additionally  also added the other python projects code

2024-10-22 10:21 UTC, Blacksujit commented
if you have any problem regarding  so please give the feedback

2024-10-22 10:27 UTC, Blacksujit reviewed
all ok

2024-10-22 12:05 UTC, d-coder111 requested changes
Morse code is not a game, so try choosing an apt folder not the game-galore folder.

2024-10-22 12:32 UTC, Blacksujit commented
Review, once and tell me

2024-10-22 12:41 UTC, Blacksujit commented on Game-Galore/AI_Guess_Animal.py
This is cool

2024-10-22 13:42 UTC, Blacksujit reviewed
All ok

2024-10-22 15:06 UTC, d-coder111 requested changes
If your project is of 2 or more files..put them under a folder and add that folder inside game-galore folder. Also, star the repo to ensure your pull request gets merged!

2024-10-22 15:14 UTC, Blacksujit commented
please , review

2024-10-22 15:15 UTC, Blacksujit reviewed
All ok

2024-10-22 15:20 UTC, d-coder111 commented
Kindly star this repo to ensure your pr gets merged.

2024-10-22 15:22 UTC, Blacksujit commented
its alerady starred🚀🚀

2024-10-22 15:26 UTC, d-coder111 approved these changes
Looks ok👍..keep coding..keep contributing ✌️

2024-10-22 15:27 UTC, merged